flowchart TB
    Q[需求] --> A1{是否需要协议级特权<br>mint 原生币 / 改 staking}
    A1 -- 是 --> M[写 x/* module]
    A1 -- 否 --> A2{是否在多条链上部署}
    A2 -- 是 --> W[写 CosmWasm 合约]
    A2 -- 否 --> A3{是否要后期升级合约本体}
    A3 -- 是 --> W
    A3 -- 否 --> A4{改一次合约就要改链<br>是不是接受?}
    A4 -- 是 --> M
    A4 -- 否 --> W