flowchart LR
    SVM[Solana Virtual Machine<br>BPF + Sealevel] --> Solana[Solana 主网]
    SVM --> Eclipse[Eclipse<br>SVM L2 on Ethereum<br>DA = Celestia]
    SVM --> Magic[MagicBlock<br>Ephemeral Rollup<br>实时游戏]
    SVM --> Sonic[Sonic<br>SVM 游戏专链]
    SVM --> Mantis[Mantis SVM]