flowchart TB
    L1[Light Client<br>chain A 跑 chain B 的轻客户端]
    L2[Connection<br>双向认证]
    L3[Channel<br>有序/无序通道]
    L4[Application<br>ICS-20 transfer / ICS-27 ICA / ICS-30 mw]
    L1 --> L2 --> L3 --> L4