mindmap
  root((Restaking 用例))
    DA 层
      EigenDA
      Avail (部分)
    Sequencer
      AltLayer
      Espresso (部分)
    Prover
      Lagrange
      Aligned Layer
    Bridge
      Renzo Bridge AVS
      ZK Bridge AVS
    Oracle
      Chainlink CCIP RMN
      Pyth Lazer
    Coprocessor
      Brevis
      Axiom