graph TB
    L1[Ethereum L1]
    L2A[Arbitrum One L2]
    L2B[OP Mainnet L2]
    L3a[xAI 游戏 L3<br>settle to Arbitrum]
    L3b[Aevo 衍生品 L3<br>settle to OP]

    L2A --> L1
    L2B --> L1
    L3a --> L2A
    L3b --> L2B