flowchart LR
    A[1 stETH<br/>未来利息 3% APR] --> SY[Pendle SY<br/>Standardized Yield]
    SY --> Split[切分到 maturity 2026-12]
    Split --> PT[1 PT-stETH-2026-12<br/>到期换 1 stETH]
    Split --> YT[1 YT-stETH-2026-12<br/>拿到期前所有利息]