graph TD
    Tang[IOTA Tangle 2015<br/>第一个 DAG]
    Hash[Hashgraph 2016<br/>gossip-about-gossip]
    Tang --> Modern[现代 DAG<br/>BFT 性 + 高吞吐]
    Hash --> Modern
    Modern --> Narwhal[Narwhal+Bullshark 2022]
    Modern --> Mysti[Sui Mysticeti 2024]
    Narwhal --> Sui[Sui Bullshark]
    Narwhal --> Aptos[Aptos Quorum Store]