graph TD
    Relay[Polkadot Relay Chain<br/>BABE+GRANDPA]
    Relay --> P1[Parachain 1<br/>Acala DeFi]
    Relay --> P2[Parachain 2<br/>Moonbeam EVM]
    Relay --> P3[Parachain 3<br/>Astar]
    Relay --> P4[...]