graph TD
    Lamport[Lamport BGP 1982<br/>3f+1 下界]
    Lamport --> Paxos[Paxos 1989<br/>crash-only]
    Paxos --> Raft[Raft 2014<br/>可理解版]
    Lamport --> PBFT[PBFT 1999<br/>第一个工程可用]
    PBFT --> Tendermint[Tendermint 2014<br/>gossip 改造]
    PBFT --> HotStuff[HotStuff 2019<br/>O(n)]
    HotStuff --> LibraBFT[LibraBFT 2019]
    LibraBFT --> DiemBFT[DiemBFT v4]
    DiemBFT --> AptosBFT[AptosBFT v4 / Jolteon]
    AptosBFT --> Raptr[Raptr 2024<br/>Aptos 当前]
    HotStuff --> Mysticeti[Sui Mysticeti 2024]