graph TD
    H[HotStuff 2019<br/>论文]
    H --> L[LibraBFT 2019<br/>Facebook Libra 实现]
    L --> D[DiemBFT v4 2021<br/>Diem rebranding]
    D --> J[Jolteon = AptosBFT v1<br/>2022 active pacemaker]
    J --> A4[AptosBFT v4 2023<br/>reputation-based leader]
    A4 --> R[Raptr 2024-09 提案]
    R --> BR[Baby Raptr 2025-06<br/>主网激活]
    BR --> Z[Zaptos 2026<br/>测试中]